//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tridion.Extensions.UI.FBI.Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tridion_Extensions_UI_FBI_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tridion_Extensions_UI_FBI_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tridion.Extensions.UI.FBI.Editor.Resources.Tridion.Extensions.UI.FBI.Strings", typeof(Tridion_Extensions_UI_FBI_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to Everyone.
        /// </summary>
        internal static string ApplyToEveryoneLabel {
            get {
                return ResourceManager.GetString("ApplyToEveryoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        internal static string BehaviourLabel {
            get {
                return ResourceManager.GetString("BehaviourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is not a valid {1}..
        /// </summary>
        internal static string DefaultErrorMessageLabel {
            get {
                return ResourceManager.GetString("DefaultErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable FBI.
        /// </summary>
        internal static string DisableFBILabel {
            get {
                return ResourceManager.GetString("DisableFBILabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error validating field {0}. {1}.
        /// </summary>
        internal static string EmailErrorMessageLabel {
            get {
                return ResourceManager.GetString("EmailErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable FBI.
        /// </summary>
        internal static string EnableFBILabel {
            get {
                return ResourceManager.GetString("EnableFBILabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBI Behaviours Info.
        /// </summary>
        internal static string FBITabLabel {
            get {
                return ResourceManager.GetString("FBITabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string HiddenLabel {
            get {
                return ResourceManager.GetString("HiddenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} exceeds the maximum allowed number of characters: {1}.
        /// </summary>
        internal static string MaximumLengthError {
            get {
                return ResourceManager.GetString("MaximumLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Length .
        /// </summary>
        internal static string MaxLengthLabel {
            get {
                return ResourceManager.GetString("MaxLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error validating field {0}. {1}.
        /// </summary>
        internal static string PhoneErrorMessageLabel {
            get {
                return ResourceManager.GetString("PhoneErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        internal static string ReadOnlyLabel {
            get {
                return ResourceManager.GetString("ReadOnlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all users.
        /// </summary>
        internal static string ShowUsersLabel {
            get {
                return ResourceManager.GetString("ShowUsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and Groups.
        /// </summary>
        internal static string UsersAndGroupsLabel {
            get {
                return ResourceManager.GetString("UsersAndGroupsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Rule.
        /// </summary>
        internal static string ValidationLabel {
            get {
                return ResourceManager.GetString("ValidationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string ZipLabel {
            get {
                return ResourceManager.GetString("ZipLabel", resourceCulture);
            }
        }
    }
}
